---
title: "Poroteo Aborto 2020"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
---

<head>
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-N1GX94R8R8"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());
  gtag('config', 'G-N1GX94R8R8');
</script>
</head> 

```{r setup, include=FALSE}
library(flexdashboard)
library(gsheet)
library(tidyverse)
library(ggthemes)
library(DT)
library(plotly)
library(janitor)
```

```{r,include=FALSE}

url <- "https://docs.google.com/spreadsheets/d/1TUTag7Majqhn5noRLLMUJ6SFJ0Phwlo-Oc1T59uSZCE/edit#gid=0"

a <- gsheet2text(url, format='csv')

df <- read_csv(a,skip = 1)

df <- df %>% 
  filter(!is.na(Cargo)) %>% 
  mutate(AbortoLegal = str_to_title(AbortoLegal))
```



# Diputados

### Resumen

```{r message=FALSE, warning=FALSE}
p1 <- df %>% 
  filter(str_detect(Cargo, 'Diputados')) %>% 
  tabyl(AbortoLegal) %>% 
  adorn_pct_formatting() %>% 
  ggplot(aes(AbortoLegal, n,label=percent, fill=AbortoLegal, text=paste(AbortoLegal,
                                                          '<br>',n,'(',percent,')')))+
  geom_col()+
  scale_fill_gdocs()+
  theme(legend.position = 'none')

ggplotly(p1, tooltip =  c("text"))
```


### Tabla

```{r}
table_diputados <- df %>% 
  filter(Cargo == 'Diputados Nacionales') %>% 
  select(Nombre, Genero,Distrito,Bloque,AbortoLegal, FuenteAbortoLegal,twitter)

datatable(table_diputados ,options = list(c(scrollY="200px", scrollX="300px", pageLength = 100)),  filter = 'top')

```

# Senadores

### Resumen

```{r message=FALSE, warning=FALSE}
p1 <- df %>% 
  filter(str_detect(Cargo, 'Senadores')) %>% 
  tabyl(AbortoLegal) %>% 
  adorn_pct_formatting() %>% 
  ggplot(aes(AbortoLegal, n,label=percent, fill=AbortoLegal, text=paste(AbortoLegal,
                                                          '<br>',n,'(',percent,')')))+
  geom_col()+
  scale_fill_gdocs()+
  theme(legend.position = 'none')

ggplotly(p1, tooltip =  c("text"))
```


### Tabla

```{r}
table_senadores <- df %>% 
  filter(Cargo == 'Senadores Nacionales') %>% 
  select(Nombre, Genero,Distrito,Bloque,AbortoLegal, FuenteAbortoLegal,twitter)

datatable(table_senadores ,options = list(c(scrollY="200px", scrollX="300px", pageLength = 100)),  filter = 'top')

```
